---
- name: Szenario 4 - Fstab Heilung (Reset)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Mounts aktualisieren
      ansible.builtin.shell: mount -a || true

    - name: Systemd Daemon neu laden (nativ)
      ansible.builtin.systemd:
        daemon_reload: yes
