---
- name: Szenario 4 - Fstab Reset
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Fstab auf Standard korrigieren
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^#.*'
        state: absent

    - name: Neustart erzwingen um Notfallmodus zu verlassen
      ansible.builtin.shell: reboot || true
