---
- name: Szenario 2 - Login Heilung (Reset)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Fehlgeschlagene Login-Zähler für den User zurücksetzen
      ansible.builtin.shell: |
        faillog -u user -r || true
        passwd -u user || true
