---
- name: Szenario 3 - DNS Sabotage
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Ungültigen DNS-Server erzwingen
      ansible.builtin.shell: |
        chattr -i /etc/resolv.conf || true
        rm -f /etc/resolv.conf || true
        echo "nameserver 10.99.99.99" > /etc/resolv.conf
