---
- name: Szenario 4 - Zerstörung der fstab (Emergency Mode)
  hosts: ziel_vm
  become: yes
  
  tasks:
    - name: Sichert die fstab als Backup und leert die aktive Datei
      ansible.builtin.shell: cp /etc/fstab /etc/fstab.bak && echo "# Zerstört durch Ansible" > /etc/fstab

    - name: Erzwingt einen sofortigen Neustart (führt zum Emergency Mode)
      ansible.builtin.reboot: