---
- name: Szenario 4 - Fstab Sabotage (Emergency Mode)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Fehlerhaften Mount-Eintrag in fstab schreiben
      ansible.builtin.shell: |
        sudo bash -c 'echo "/dev/nonexistent /mnt/ungueltig ext4 defaults 0 0" >> /etc/fstab'
