---
- name: Szenario 5 - SSH Sabotage (Dienst stoppen)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: SSH-Dienst stoppen und deaktivieren
      ansible.builtin.shell: |
        sudo systemctl stop ssh || true
        sudo systemctl disable ssh || true
