---
- name: Szenario 6 - Docker Volume Rechte-Fehler
  hosts: ziel_vm
  become: yes
  
  tasks:
    - name: Entzieht die Lese- und Schreibrechte fuer ein fiktives Docker-Volume
      ansible.builtin.file:
        path: /var/lib/docker/volumes/
        mode: '0000' # Niemand darf mehr lesen oder schreiben
        recurse: yes