---
- name: Szenario 6 - Docker Sabotage (Dienst stoppen / Loop)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Docker-Dienst stoppen und deaktivieren
      ansible.builtin.shell: |
        sudo systemctl stop docker || true
        sudo systemctl disable docker || true
