---
- name: Szenario 8 - NTP Heilung (Reset)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Zeitsynchronisation wieder aktivieren
      ansible.builtin.shell: |
        sudo timedatectl set-ntp true || true
        sudo systemctl restart systemd-timesyncd || true
