---
- name: Szenario 8 - NTP Sabotage (Zeit verstellen)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Zeitsynchronisation deaktivieren und Datum in die Vergangenheit setzen
      ansible.builtin.shell: |
        sudo timedatectl set-ntp false || true
        sudo date -s "2020-01-01 12:00:00" || true
