---
- name: Szenario 9 - Hosts Sabotage (Lokale DNS manipulieren)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Falsche IP für localhost in /etc/hosts erzwingen
      ansible.builtin.shell: |
        sudo bash -c 'echo "10.99.99.99 localhost" > /etc/hosts'
