---
- name: Szenario 9 - Hosts Heilung (Reset)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Standard /etc/hosts wiederherstellen
      ansible.builtin.shell: |
        sudo bash -c 'echo -e "127.0.0.1\tlocalhost\n::1\tlocalhost ip6-localhost ip6-loopback" > /etc/hosts'
