---
- name: Szenario 10 - Sudo Heilung (Reset)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Benutzer 'user' wieder zur Sudo-Gruppe hinzufügen
      ansible.builtin.shell: |
        sudo usermod -aG sudo user || true
