---
- name: Szenario 10 - Sudo Sabotage (Rechte entziehen)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Benutzer 'user' aus der Sudo-Gruppe entfernen
      ansible.builtin.shell: |
        sudo gpasswd -d user sudo || true
