---
- name: Szenario 11 - Bashrc Sabotage (Login-Abbruch)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Exit-Befehl in die .bashrc des Users schreiben
      ansible.builtin.shell: |
        sudo bash -c 'echo "exit" >> /home/user/.bashrc'
