---
- name: Szenario 11 - Bashrc Heilung (Reset)
  hosts: ziel_vm
  become: yes

  tasks:
    - name: Standard .bashrc wiederherstellen
      ansible.builtin.shell: |
        sudo cp /etc/skel/.bashrc /home/user/.bashrc
        sudo chown user:user /home/user/.bashrc
